build:
    tests:
        override:
            -
                command: phpunit
                coverage:
                    file: coverage.clover
                    format: php-clover
filter:
    paths:
        - 'src/*'
        - 'tests/*'

tools:
    php_code_sniffer:
        config:
            standard: PSR2
